### ISSUE TITLE
Set a standard image size for image in cards of recent events

### ISSUE THREAD

**Issue by BISHALTWR** [computerclubkec/computerclubkec.github.io#100]
### Lets make the cards consistent

![issue](https://github.com/user-attachments/assets/2a2969ee-b62b-4a6f-9169-f63785cc666b)

**Comment by prabhavpokharel** [comment]
Computer Club mostly uses two aspect ratios for event designs. So, I think we should keep it accordingly.

### Aspect Ratios
- 1:1 (mostly 1080px x 1080px) - Used as event posters and social media posts. I prefer using this as event thumbnails.
- 5:3 (mostly 60in x 36in) - Used as event banner flex.
