### ISSUE TITLE
Registration form not opening for workshop

### ISSUE THREAD

**Issue by Amulya-Codes** [computerclubkec/computerclubkec.github.io#111]
Description: The registration form for the workshop isn't loading when I click the "Register Now" button.  Below are the details of the issue:

Steps to reproduce:

Go to the workshop page: [Workshop URL]
Scroll down to the "Register Now" button
Click on the button
Expected behavior: The registration form should open in a modal or redirect to the registration page.

Actual behavior: Clicking on the "Register Now" button does not open the form or show any error message.

**Comment by BISHALTWR** [comment]
Most of the events are dummy events to make testing easier. So, this is not an issue yet. Thank you for taking the time to review though.

> You are welcome to contribute in other aspects.
