### ISSUE TITLE
Add to calendar for Events

### ISSUE THREAD

**Issue by gaurovgiri** [computerclubkec/computerclubkec.github.io#118]
Having an `Add to Calendar` button that provides `.ics` for the event might be a good feature.

**Comment by ajogseneca** [comment]
@gaurovgiri I can try to work on this

**Comment by ajogseneca** [comment]
Sorry for not posting any updates, i was having some issues on my side, this issue will be completed by this week !

**Comment by ajogseneca** [comment]
@BISHALTWR Issue is updated with PR #127
