### ISSUE TITLE
renaming 'Past Events'/'Recent Events' to 'Past Activities'/'Recent Activities'

### ISSUE THREAD

**Issue by prabhavpokharel** [computerclubkec/computerclubkec.github.io#121]
If we replace the 'Past Events' with 'Past Activities' here, then we can include not only public events but a lot of things carried out by the Computer Club in this section. We can include things like, internal sessions, editorial board revamp, partnerships, etc.

### Preview
![image](https://github.com/user-attachments/assets/3692cf1d-99cd-466f-b1f9-9653f7c96994)

**Comment by BISHALTWR** [comment]
I totally agree.

**Comment by rpandox** [comment]
I think it is good
what do you think @gaurovgiri

**Comment by gaurovgiri** [comment]
Sounds Good!
