### ISSUE TITLE
At home page, display the only the current year's Executive Members

### ISSUE THREAD

**Issue by gaurovgiri** [computerclubkec/computerclubkec.github.io#128]
![Screenshot 2024-10-25 at 1 12 36 PM](https://github.com/user-attachments/assets/c21ef2b0-c990-416f-87d0-e82494d0b001)

Need to remove previous year executive member's option from the home page but will be able to view them through About us Page.

## Task
- Remove the option to view `2023/24` from the home page
- Remove the `2024/2025` as well but make sure to display the members of `2024/2025`

*I expect non-members to contribute on this*

**Comment by ajogseneca** [comment]
@gaurovgiri i can fix this issue !

**Comment by ajogseneca** [comment]
So technically you don't need the old options there just put that in the About Us page ?

**Comment by ajogseneca** [comment]
I have added a fix for this, Pull Request #136
