### ISSUE TITLE
Add Dedicated Projects Page and Update Navigation for Project Section

### ISSUE THREAD

**Issue by prabhavpokharel** [computerclubkec/computerclubkec.github.io#139]
Currently, the Computer Club website only displays projects on the homepage under the "Projects" section, with no dedicated page for browsing more projects. Additionally, there is no link to the projects section in the navigation bar, making it difficult for users to access or locate projects across the site. Furthermore, the "See More" button in the project section redirects to a 404 error page.

### Expected Behavior
1. Dedicated Projects Page: Create a standalone page where users can view and explore all projects.
2. Update Navigation: Add a "Projects" link to the navigation bar to improve accessibility to the projects section.
3. Fix "See More" Button: Ensure that the "See More" button in the project section correctly links to the new dedicated Projects page instead of leading to a 404 page.

**Comment by cduarte3** [comment]
Hello @prabhavpokharel, can you please assign me this issue?

**Comment by prabhavpokharel** [comment]
@cduarte3 Thanks for your interest but we already have a PR for this.
