### ISSUE TITLE
Font family is missing

### ISSUE THREAD

**Issue by aayush105** [computerclubkec/computerclubkec.github.io#21]
It seems that the design requires Montserrat and Inter Fonts which should be available for tailwind to use.

### Suggestion:
- Tailwind will use the font through `class="font-[Montserrat]"`

**Comment by GaurangMapuskar** [comment]
Assign this issue to me @aayush105

**Comment by wittyparth** [comment]
Can I work on this issue?

**Comment by rpandox** [comment]
@SamratAdhikari is there any update on this issue?

**Comment by prabhavpokharel** [comment]
The issue now has been solved.
