### ISSUE TITLE
[SETUP]: Dockerfile missing

### ISSUE THREAD

**Issue by gaurovgiri** [computerclubkec/computerclubkec.github.io#3]
Need a Dockerfile and compose file so that any contributor can easily run the project without bearing the trouble of installing the ruby and jekyll.
Things to make sure:
- The container is build through the Dockerfile
- The volume should bind between the host and the container

**Comment by aayush105** [comment]
I will work on this issue, assign it to me.

**Comment by gaurovgiri** [comment]
Sure go ahead, i will assign this to you.
