### ISSUE TITLE
[ADD] : Recent Event section

### ISSUE THREAD

**Issue by aayush105** [computerclubkec/computerclubkec.github.io#49]
Add this section under the event section:

![image](https://github.com/user-attachments/assets/4e52eb86-24e7-4ce0-b81e-24dc71f70099)

**Comment by gaurovgiri** [comment]
I would like to work on this issue.

**Comment by aayush105** [comment]
> I would like to work on this issue.

Ok i have assigned this to you. @gaurovgiri
