### ISSUE TITLE
[FEAT] Make Event Card clickable

### ISSUE THREAD

**Issue by gaurovgiri** [computerclubkec/computerclubkec.github.io#56]
Every event has its markdown in Events collection. When a user clicks on the card itself, redirect them to {{ event.url }}.
Also, it would be better if a hovering effect/animation is used when cursor is placed on the event card

**Comment by prabhavpokharel** [comment]
Which one? The "Upcoming Events" card right? @gaurovgiri

**Comment by gaurovgiri** [comment]
@prabhavpokharel Every event cards. inside the loop of the event, you can access the link to the event through built-in data {{ event.url }}
