### ISSUE TITLE
[FEAT] Add Members Section

### ISSUE THREAD

**Issue by gaurovgiri** [computerclubkec/computerclubkec.github.io#57]
Executive Members section is required. It requires storing the information of Members in yaml file for each year. and displaying them as follow:

<img width="509" alt="Screenshot 2024-10-06 at 11 50 30 PM" src="https://github.com/user-attachments/assets/cccefcb1-3e4e-440b-8cb8-98be88a1d071">

**Comment by aayush105** [comment]
I will do it, assign it to me.

**Comment by gaurovgiri** [comment]
okie
