### ISSUE TITLE
[FEAT] Implement End Date in event card

### ISSUE THREAD

**Issue by gaurovgiri** [computerclubkec/computerclubkec.github.io#58]
![Screenshot 2024-10-07 at 2 52 13 AM](https://github.com/user-attachments/assets/df0cb7b3-8db0-493c-91ca-efbf32bf54c4)

If a event has a span of multiple days, then it should display the duration from starting date to end date.
Each event has `date` and `end_date` which can be used to display. if it is a single date event donot display the end date, but if it has a span of multiple days then display it like:

`Tue, Oct 1, 2024 - Thu, Oct 3, 2024`

**Comment by rpandox** [comment]
@gaurovgiri , can you assign this to me

**Comment by gaurovgiri** [comment]
Sure you can start, I'm in phone right so I can't assign you through github, but you can start working.

**Comment by rpandox** [comment]
Thankyou!!

**Comment by prabhavpokharel** [comment]
Can't wait to see it!
