### ISSUE TITLE
Section tag missing in home page

### ISSUE THREAD

**Issue by gaurovgiri** [computerclubkec/computerclubkec.github.io#59]
Metrics Banner, Upcoming Events and brand collaboration are missing `<section>` tag.

**Comment by mpa-LHutchinson** [comment]
Hi @gaurovgiri, can you assign this issue to me and give it the hacktoberfest label? I'll get working on it as soon as I can today.

**Comment by gaurovgiri** [comment]
Sure go ahead. The repo itself has the hackotberfest label. Also give the section with proper id name to metrics banner, upcoming events, recent events and brand colab.

**Comment by mpa-LHutchinson** [comment]
@gaurovgiri I updated this issue now with #61
