### ISSUE TITLE
Not responsive on smaller screens

### ISSUE THREAD

**Issue by irekponor** [computerclubkec/computerclubkec.github.io#65]
The current implementation of the web page displays significant responsiveness issues when viewed on smaller screens. Key breakpoints are not properly defined, leading to layout distortions and overlapping elements. The CSS does not have effective media queries. This should be looked into.

**Comment by aayush105** [comment]
> The current implementation of the web page displays significant responsiveness issues when viewed on smaller screens. Key breakpoints are not properly defined, leading to layout distortions and overlapping elements. The CSS does not have effective media queries. This should be looked into.

You can work on this issue if you want to contribute. @irekponor
