### ISSUE TITLE
Implement Email Service through contact page.

### ISSUE THREAD

**Issue by BISHALTWR** [computerclubkec/computerclubkec.github.io#71]
- Currently the `Send` button in Contact page just logs the form content.

**Comment by BISHALTWR** [comment]
Do this after #69 is merged.

**Comment by BISHALTWR** [comment]
@gaurovgiri 
Do you have anything planned for how to approach this? 
Is using `mailto` fine?

**Comment by gaurovgiri** [comment]
@BISHALTWR I think the best for right now is to implement `mailto`. We can implement third party services for email but the issue with the client side application is that the secrets of the 3rd party app will be publicly visible. So yeah best thing to do right now is to implement mail to. Also could you check if we can send subject and body as well in the parameters.

**Comment by BISHALTWR** [comment]
Alright, i will look into it.
