### ISSUE TITLE
[ADD: ] KEC Lite Page

### ISSUE THREAD

**Issue by BISHALTWR** [computerclubkec/computerclubkec.github.io#79]
```py
None
```

**Comment by BISHALTWR** [comment]
> Hardcoding the content into HTML should be fine for this?? @gaurovgiri

**Comment by gaurovgiri** [comment]
I think using the event layout would be great for this. And define the KEC Lite within `_events` collection. This will make it easy to bring KEC LITE in upcoming page just by changing `completed` and `date` parameters. Currently, there is not `event.html` layout. There is raised issued which you can find at #55.

**Comment by gaurovgiri** [comment]
Oh wait, the issue was that tailwind was suppressing the styling of markdown. Example, a `<h2>` would be created if `##` was used, but it wasn't seen directly. Just realized you can directly use html tags inside the content part of markdown and use tailwind css there.

**Comment by gaurovgiri** [comment]
So for this issue:
- First Event Layout Needs to be created ( I will create a PR for this )
- Create an event markdown for `KEC LITE` with name `kec-lite.markdown`
- In the content part, use html tags and tailwind to write about KEC LITE.

**Comment by BISHALTWR** [comment]
I am thinking about adding option to manually set the layout for events if desired.

There will be a `maual: true/false` in metadata(if thats what it is called) of markdown for if we need different layout than the default for the whole event page. 

I will include that in upcoming PR and lets discuss if it feels alright

**Comment by BISHALTWR** [comment]
@gaurovgiri @prabhavpokharel @rpandox 

> Approximate number of participants in KEC lite?

**Comment by rpandox** [comment]
1200 in around two days

**Comment by BISHALTWR** [comment]
Sounds about right. Thanks.
