### ISSUE TITLE
[FEAT]: Make the club logo clickable that redirects to home

### ISSUE THREAD

**Issue by gaurovgiri** [computerclubkec/computerclubkec.github.io#82]
<img width="775" alt="Screenshot 2024-10-12 at 4 47 17 PM" src="https://github.com/user-attachments/assets/ca7dce79-578d-4164-a10f-ac4d65b5db76">

## Current Behaviour
Nothing happens when clicked on the logo

## Expected Behaviour
On clicking the logo, it should redirect to the home page.

*I would like contributors outside the organization to contribute on this.*

**Comment by shaswat-satyam** [comment]
Can you assign this issue to me?

**Comment by gaurovgiri** [comment]
Sure, you can start working. Make sure you star the repo as well.
