### ISSUE TITLE
Active page link's color is conflicting with "Contact us" button

### ISSUE THREAD

**Issue by prabhavpokharel** [computerclubkec/computerclubkec.github.io#86]
This is what I am talking about:
![image](https://github.com/user-attachments/assets/ba8422b9-8557-41a0-8ce1-3effa2313b4b)

The active page color logic should be detached from the button only.

**Comment by gaurovgiri** [comment]
True True

**Comment by BISHALTWR** [comment]
branched from the wrong spot..

Will open PR after PR #85 is merged
