### ISSUE TITLE
Ordering of recent events is not right

### ISSUE THREAD

**Issue by BISHALTWR** [computerclubkec/computerclubkec.github.io#87]
- This is what i mean
![This](https://github.com/user-attachments/assets/a43cd119-45c2-473e-b45a-64723a0e2f3e)

> Most recent event must be shown first and not the other way around. Also, should we limit the number of recent events shown ?

- P.S. Marked `bug` since it is bugging me.

**Comment by gaurovgiri** [comment]
True True.
