### ISSUE TITLE
[ADD!]: Need to create About us Page

### ISSUE THREAD

**Issue by gaurovgiri** [computerclubkec/computerclubkec.github.io#91]

**Comment by prabhavpokharel** [comment]
I shall see this

**Comment by gaurovgiri** [comment]
Okay, Change the status to Progress in the Project section located at right bar once you start working.

**Comment by prabhavpokharel** [comment]
Sure!

**Comment by prabhavpokharel** [comment]
It seems that I do not have access to modify changes in the Project section, @gaurovgiri.

**Comment by gaurovgiri** [comment]
Got it. You can start working, I will fix it later
