### ISSUE TITLE
[ADD]: Create Blog Page with Blog Cards

### ISSUE THREAD

**Issue by gaurovgiri** [computerclubkec/computerclubkec.github.io#95]
![Screenshot 2024-10-14 at 3 02 39 PM](https://github.com/user-attachments/assets/f21afa28-e4d6-4e15-a7c4-1058479190ea)

A separate Blog Collection needs to be created for this.

**Comment by BISHALTWR** [comment]
I think we should create create some `issues for writing blogs and assign it to non-code contributors` from computer club
 and such before starting to work on blog page.

**Comment by gaurovgiri** [comment]
Sounds about right. We have to discuss this later.

**Comment by ajogseneca** [comment]
Hi i would like to contribute to this part of your website. I already made some progress 
![image](https://github.com/user-attachments/assets/2e2232ee-f076-4f61-98b9-8a182713c8d3)

I had a chat with @gaurovgiri .
I also request to add me as assignee for this issue.

**Comment by ajogseneca** [comment]
I have updated with a Pull Request #113

**Comment by ajogseneca** [comment]
@gaurovgiri Do you want me to close this issue after assigning this to me ?

**Comment by gaurovgiri** [comment]
Oh wait, I forgot to close this issue.
